.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,7 +2,7 @@ name: Deploy to GitHub Pages
 
 on:
   push:
-    branches: [main]  # Set this to your default branch
+    branches: [main]
   pull_request:
     branches: [main]
 
@@ -24,7 +24,7 @@ jobs:
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
-        node-version: '22'  # Adjust this to your project's Node.js version
+        node-version: '22'
 
     - name: Install dependencies
       run: yarn install
@@ -40,6 +40,18 @@ jobs:
         echo "VITE_GITHUB_ACCESS_TOKEN_PART1=${{ secrets.GITHUB_ACCESS_TOKEN_PART1 }}" >> .env.local
         echo "VITE_GITHUB_ACCESS_TOKEN_PART2=${{ secrets.GITHUB_ACCESS_TOKEN_PART2 }}" >> .env.local
 
+    - name: Test GitHub API Authentication
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN_PART1 }}${{ secrets.GITHUB_ACCESS_TOKEN_PART2 }}
+      run: |
+        response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user)
+        if [ $response -eq 200 ]; then
+          echo "GitHub API authentication successful"
+        else
+          echo "GitHub API authentication failed with status code: $response"
+          exit 1
+        fi
+
     - name: Build
       run: yarn build
 
@@ -48,5 +60,5 @@ jobs:
       if: github.ref == 'refs/heads/main'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./dist  # Adjusted this to the typical Vite build output directory
-        publish_branch: gh-p
+        publish_dir: ./dist
+        publish_branch: gh-pages
